from handlers.book_handlers import (
    handle_add_address,
    handle_add_birthday,
    handle_add_contact,
    handle_add_email,
    handle_delete_contact,
    handle_find_birthday,
    handle_find_contact,
    handle_find_email,
    handle_show_address,
    handle_show_all_contacts,
    handle_show_birthday,
    handle_show_email,
    handle_show_phone,
    handle_upcoming_birthdays,
    handle_update_birthday,
    handle_update_email,
    handle_update_phone,
)
from handlers.common_handlers import handle_exit, handle_hello, handle_help
from handlers.notes_handlers import (
    handle_add_note,
    handle_add_tag,
    handle_change_tag,
    handle_delete_note,
    handle_delete_tag,
    handle_find_notes_by_tag,
    handle_show_contact_notes,
    handle_update_note,
)

COMMAND_TO_HANDLER = {
    "add-contact": handle_add_contact,
    "find-contact": handle_find_contact,
    "delete-contact": handle_delete_contact,
    "all-contact": handle_show_all_contacts,
    "update-phone": handle_update_phone,
    "show-phone": handle_show_phone,
    "add-birthday": handle_add_birthday,
    "find-birthday": handle_find_birthday,
    "show-birthday": handle_show_birthday,
    "update-birthday": handle_update_birthday,
    "upcoming-birthdays": handle_upcoming_birthdays,
    "add-email": handle_add_email,
    "update-email": handle_update_email,
    "find-email": handle_find_email,
    "show-email": handle_show_email,
    "show-address": handle_show_address,
    "add-address": handle_add_address,
    "add-note": handle_add_note,
    "delete-note": handle_delete_note,
    "update-note": handle_update_note,
    "show-contact-notes": handle_show_contact_notes,
    "find-notes-by-tag": handle_find_notes_by_tag,
    "add-tag": handle_add_tag,
    "change-tag": handle_change_tag,
    "delete-contact-tag": handle_delete_tag,
    "hello": handle_hello,
    "close": handle_exit,
    "exit": handle_exit,
    "help": handle_help,
}
